version: '3.9'
services:
  my-golang-app:
    build: .
    image: my-golang-app
    container_name: my-golang-app
    restart: "no"
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      KAFKA_HOST: ${KAFKA_HOST}
      KAFKA_PORT: ${KAFKA_PORT}
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      MEMCACHED_HOST: ${MEMCACHED_HOST}
      MEMCACHED_PORT: ${MEMCACHED_PORT}
      MEMCACHED_LIVE_TIME: ${MEMCACHED_LIVE_TIME}
    depends_on:
      - ${DATABASE_HOST}
      - ${KAFKA_HOST}
      - ${MEMCACHED_HOST}

  postgresql:
    image: postgres:latest
    container_name:  ${DATABASE_HOST}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"

  memcached:
    image: memcached:latest
    container_name: ${MEMCACHED_HOST}
    ports:
      - "${MEMCACHED_PORT}:${MEMCACHED_PORT}"

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: ${KAFKA_HOST}
    ports:
      - '${KAFKA_PORT}:${KAFKA_PORT}'
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_HOST}:${KAFKA_PORT} # specifies the advertised Kafka listener
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 # specifies the Zookeeper connection string for Kafka
      - ALLOW_PLAINTEXT_LISTENER=yes # allows plain text listeners for Kafka
      - KAFKA_CREATE_TOPICS="${KAFKA_TOPIC}:1:1" # specifies a topic to create for Kafka
    depends_on:
      - zookeeper
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes # allows anonymous logins for Zookeeper
    ports:
      - '2181:2181'
