version: '3.9'
services:
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: "mykafka"
    ports:
      - '${KAFKA_PORT}:${KAFKA_PORT}'
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_HOST}:${KAFKA_PORT} # specifies the advertised Kafka listener
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 # specifies the Zookeeper connection string for Kafka
      - ALLOW_PLAINTEXT_LISTENER=yes # allows plain text listeners for Kafka
      - KAFKA_CREATE_TOPICS="${KAFKA_TOPIC}:1:1" # specifies a topic to create for Kafka
    depends_on:
      - zookeeper
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes # allows anonymous logins for Zookeeper
    ports:
      - '2181:2181'
